### ISSUE TITLE
have throw a error message

### ISSUE THREAD

**Issue by hygine** [davek44/utility#1]
File "./fastq_sample.py", line 102
    print(header, file=out_open, end='')
                      ^
SyntaxError: invalid syntax

my run shell : python ./fastq_sample.py 100000 ./P1_1.fq ./P1_2.fq ./P1_sample_1.fq  ./P1_sample_2.fq

**Comment by davek44** [comment]
I'm transitioning to python3, so this repository is going to be a mix for the next year or so. You can fix any errors like this one by adding the following line before the imports:

`from __future__ import print_function`

I fixed fastq_sample.py, so it should work now.
